Updating google analytics metrics getter
fhdsl/metricminer pull request #73
Opened 2024-02-26 20:23 UTC by cansavvy

### Purpose/implementation Section

#### What changes are being implemented in this Pull Request?

Fixing up some things for usability and DRYness purposes. 

The google analytics `all_ga_metrics()` is being deprecated changed so it can take property ids instead of just taking all properties from an account. 

In order to do this, we needed to make a new function that will allow a display name for a property to be retrieved.

2024-02-26 20:26 UTC, cansavvy commented
I also ran styler::style_dir("R") so a lot of the changes have to do with that.

2024-02-26 21:12 UTC, cansavvy commented on R/google-analytics.R
> +get_multiple_ga_metrics <- function(account_id = NULL, property_ids = NULL, token = NULL, dataformat = "dataframe",
And this function got reworked. Can you take a look and see what you think of the changes and if you have recommendations? @howardbaek

2024-03-01 19:39 UTC, howardbaek commented on R/google-analytics.R
> +#' Get all property information for a particular property id
This isn't working for me. As documented, I made sure to check the box `See and download your Google Analytics data.` on the OAuth screen:

<img width="536" alt="Screenshot 2024-03-01 at 11 36 49 AM" src="https://github.com/fhdsl/metricminer/assets/50791792/996f5f6d-0b9d-4847-81d7-774e4386d092">

However, when I see

```
> property_info <- get_ga_property_info(property_id = "422558989")
Using user-supplied cached tokens stored using authorize("google")


Error in request_ga(token = token, url = paste0("https://analyticsadmin.googleapis.com/v1alpha/properties/",  : 
  API request failed:{
  "error": {
    "code": 403,
    "message": "The caller does not have permission",
    "status": "PERMISSION_DENIED"
  }
}
```

2024-03-01 19:43 UTC, howardbaek commented on R/google-analytics.R
> +get_multiple_ga_metrics <- function(account_id = NULL, property_ids = NULL, token = NULL, dataformat = "dataframe",
Same as above:

```
> some_properties <- get_multiple_ga_metrics(property_ids = c("422671031", "422558989"))
Using user-supplied cached tokens stored using authorize("google")


Error in request_ga(token = token, url = paste0("https://analyticsadmin.googleapis.com/v1alpha/properties/",  : 
  API request failed:{
  "error": {
    "code": 403,
    "message": "The caller does not have permission",
    "status": "PERMISSION_DENIED"
  }
}
```

2024-03-01 19:45 UTC, howardbaek requested changes
I think we may have to address the Google scopes as the functions here are denying permission.

2024-03-05 16:43 UTC, cansavvy commented on R/google-analytics.R
> +#' Get all property information for a particular property id
@howardbaek Did you login with ITCR Gmail or your own personal gmail? If you logged in with your own gmail, you don't have access to this property id so it wouldn't work.

2024-03-05 16:43 UTC, cansavvy commented on R/google-analytics.R
> +#' Get all property information for a particular property id
I should make that more clear in the example

2024-03-05 18:20 UTC, cansavvy commented
We tested this in a pair programming session and found out it was because Howard was trying to access a property id with the hutchgmail account that it does not have access to. Tried to fix the docs appropriately.

2024-03-05 19:51 UTC, merged